version: "3.7"

services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    nginx:
        image: nginx:1.25.3
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    postgres:
        image: postgres:16.1
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE:-postgres}
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD-postgres}
            POSTGRES_SCHEMA: ${DB_SCHEMA:-public}
        volumes:
            - ./.docker/postgresql:/var/lib/postgresql
        ports:
            - "5432:5432"
        networks:
            - laravel

    redis:
        image: redis:7.2.3
        container_name: redis
        restart: unless-stopped
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        networks:
            - laravel

networks:
    laravel:
        driver: bridge